# project name
name: 'ch_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project (profiles.yml).
profile: 'analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# dbt will build all models in the prd/ directory as tables.
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  +engine: ReplicatedMergeTree
  ch_dbt: # name of your project
    # Config indicated by + and applies to all files under
    # models/prd/ folder
    prd:
      +materialized: table
      
    # Config indicated by + and applies to all files under
    # models/google_analytics/ folder
    google_analytics:
      +materialized: view

seeds:
  +engine: ReplicatedMergeTree
